export const CHANGE_LANG = 'CHANGE_LANG';
export const CHANGE_TEMPER_UNIT = 'CHANGE_TEMPER_UNIT';
export const CHANGE_CITY = 'CHANGE_CITY';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_CITY_SWITCH = 'SHOW_CITY_SWITCH';
export const SELECT_CITY = 'SELECT_CITY';
export const DELETE_CITY = 'DELETE_CITY';